package Primitives;

public enum MessageType {
    REGISTER_NODE,
    HOST_DISCOVERY,
    GET_TOTAL_COUNT,
    MAP_TOTAL_COUNT,
    REDUCE_TOTAL_COUNT,
    REDUCE_MANAGER_STATE,
    TOTAL_COUNT_ARRIVAL,
    MANAGER_STATE_ARRIVAL,
    GET_TOTAL_COUNT_RESPONSE,
    REFRESH_CUSTOMER,
    REFRESH_MANAGER,
    FILTER,
    TOTAL_STORES_ARRIVAL,
    RATE,
    RESULT,
    PURCHASE,
    ADD_STORE,
    TOTAL_REVENUE_PER_PRODUCT_TYPE,
    TOTAL_REVENUE_PER_FOOD_CATEGORY,
    ADD_STORE_ARRIVAL,
    FOOD_CATEGORIES_ARRIVAL,
    REDUCE_FOOD_CATEGORIES,
    REDUCE_TOTAL_REVENUE,
    TOTAL_REVENUE_ARRIVAL,
    EDIT_STORE
};
